Repository HuskyDreaming/MedievalBrewery, pull requests merged in 2024-10, with the labels that each got.

#7 #6 Great Update
  .idea/misc.xml
  pom.xml
  src/main/java/com/huskydreaming/medieval/brewery/MedievalBreweryPlugin.java
  src/main/java/com/huskydreaming/medieval/brewery/commands/BreweryCommand.java
  src/main/java/com/huskydreaming/medieval/brewery/data/Effect.java
  src/main/java/com/huskydreaming/medieval/brewery/data/Ingredient.java
  src/main/java/com/huskydreaming/medieval/brewery/data/Quality.java
  src/main/java/com/huskydreaming/medieval/brewery/data/Recipe.java
  src/main/java/com/huskydreaming/medieval/brewery/handlers/implementations/BreweryHandlerImpl.java
  src/main/java/com/huskydreaming/medieval/brewery/handlers/implementations/ConfigHandlerImpl.java
  src/main/java/com/huskydreaming/medieval/brewery/handlers/implementations/LocalizationHandlerImpl.java
  src/main/java/com/huskydreaming/medieval/brewery/handlers/interfaces/ConfigHandler.java
  src/main/java/com/huskydreaming/medieval/brewery/handlers/interfaces/LocalizationHandler.java
  src/main/java/com/huskydreaming/medieval/brewery/listeners/PlayerListener.java
  src/main/java/com/huskydreaming/medieval/brewery/repositories/implementations/BreweryRepositoryImpl.java
  src/main/java/com/huskydreaming/medieval/brewery/repositories/implementations/QualityRepositoryImpl.java
  src/main/java/com/huskydreaming/medieval/brewery/repositories/implementations/RecipeRepositoryImpl.java
  src/main/java/com/huskydreaming/medieval/brewery/repositories/interfaces/QualityRepository.java
  src/main/java/com/huskydreaming/medieval/brewery/repositories/interfaces/RecipeRepository.java
  src/main/java/com/huskydreaming/medieval/brewery/utils/TimeUtil.java
  src/main/resources/plugin.yml
Labels: bug, enhancement

#12 Readded the License File
  LICENSE
  README.md
Labels: documentation

#15 #14 Add Custom Model Data To Recipe Ingredients
  pom.xml
  src/main/java/com/huskydreaming/medieval/brewery/MedievalBreweryPlugin.java
  src/main/java/com/huskydreaming/medieval/brewery/commands/BreweryCommand.java
  src/main/java/com/huskydreaming/medieval/brewery/data/Brewery.java
  src/main/java/com/huskydreaming/medieval/brewery/data/Ingredient.java
  src/main/java/com/huskydreaming/medieval/brewery/data/Item.java
  src/main/java/com/huskydreaming/medieval/brewery/data/Recipe.java
  src/main/java/com/huskydreaming/medieval/brewery/enumerations/BreweryStatus.java
  src/main/java/com/huskydreaming/medieval/brewery/handlers/implementations/BreweryHandlerImpl.java
  src/main/java/com/huskydreaming/medieval/brewery/handlers/implementations/LocalizationHandlerImpl.java
  src/main/java/com/huskydreaming/medieval/brewery/handlers/interfaces/BreweryHandler.java
  src/main/java/com/huskydreaming/medieval/brewery/handlers/interfaces/LocalizationHandler.java
  src/main/java/com/huskydreaming/medieval/brewery/listeners/InventoryListener.java
  src/main/java/com/huskydreaming/medieval/brewery/listeners/PlayerListener.java
  src/main/java/com/huskydreaming/medieval/brewery/repositories/implementations/QualityRepositoryImpl.java
  src/main/java/com/huskydreaming/medieval/brewery/repositories/implementations/RecipeRepositoryImpl.java
  src/main/java/com/huskydreaming/medieval/brewery/storage/Message.java
  src/main/java/com/huskydreaming/medieval/brewery/utils/RandomCollection.java
  src/main/resources/plugin.yml
Labels: enhancement
